// <auto-generated />
using AegisLink.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AegisLink.Server.Migrations
{
    [DbContext(typeof(AegisLinkDbContext))]
    [Migration("20260406033217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AegisLink.Server.Data.UserKey", b =>
                {
                    b.Property<string>("AegisId")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AegisId");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.ToTable("UserKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
