using AegisLink.Shared;
using Microsoft.JSInterop;

namespace Aegis_Link_VEIL.Services;

/// <summary>
/// Provides contact CRUD operations through the JavaScript crypto/contact layer.
/// </summary>
/// <remarks>
/// Contact data stays in browser storage and this service exposes a clean async API for pages.
/// </remarks>
public class ContactService
{
    // JS runtime bridge used for contact storage calls.
    private readonly IJSRuntime _js;

    /// <summary>
    /// Creates a new contact service instance.
    /// </summary>
    /// <param name="js">JavaScript runtime used for browser interop calls.</param>
    public ContactService(IJSRuntime js)
    {
        _js = js;
    }

    /// <summary>
    /// Loads all contacts and returns them sorted by nickname.
    /// </summary>
    /// <returns>Sorted contact list.</returns>
    public async Task<List<Contact>> GetAllAsync()
    {
        // Load contacts from browser storage and sort by nickname for stable UI order.
        var contacts = await _js.InvokeAsync<List<Contact>>("aegisCrypto.loadContacts");
        return contacts.OrderBy(c => c.Nickname).ToList();
    }

    /// <summary>
    /// Finds one contact by Aegis id.
    /// </summary>
    /// <param name="aegisId">Contact Aegis id to search for.</param>
    /// <returns>Matching contact or <c>null</c> when not found.</returns>
    public async Task<Contact?> GetByIdAsync(string aegisId)
    {
        // This does a simple in-memory lookup after loading all contacts.
        var contacts = await _js.InvokeAsync<List<Contact>>("aegisCrypto.loadContacts");
        return contacts.FirstOrDefault(c => c.AegisId == aegisId);
    }

    /// <summary>
    /// Saves or updates a contact.
    /// </summary>
    /// <param name="contact">Contact payload to save.</param>
    public async Task SaveAsync(Contact contact)
    {
        await _js.InvokeVoidAsync("aegisCrypto.saveContact", contact);
    }

    /// <summary>
    /// Deletes a contact by Aegis id.
    /// </summary>
    /// <param name="aegisId">Aegis id to remove.</param>
    public async Task DeleteAsync(string aegisId)
    {
        await _js.InvokeVoidAsync("aegisCrypto.deleteContact", aegisId);
    }

    /// <summary>
    /// Gets a deterministic UI colour for a contact id.
    /// </summary>
    /// <param name="aegisId">Contact Aegis id.</param>
    /// <returns>Colour string generated by the JS helper.</returns>
    public async Task<string> GetColourAsync(string aegisId)
    {
        // Colour is derived from the id so each contact keeps a consistent colour.
        return await _js.InvokeAsync<string>("aegisCrypto.colourForId", aegisId);
    }

    /// <summary>
    /// Checks if a contact exists for a given Aegis id.
    /// </summary>
    /// <param name="aegisId">Aegis id to check.</param>
    /// <returns><c>true</c> if the contact exists; otherwise <c>false</c>.</returns>
    public async Task<bool> ExistsAsync(string aegisId)
    {
        // Load from storage and perform a quick Any() check.
        var contacts = await _js.InvokeAsync<List<Contact>>("aegisCrypto.loadContacts");
        return contacts.Any(c => c.AegisId == aegisId);
    }
}
